<script setup>
import { computed, onMounted, ref } from 'vue'
import { getCourierParcels } from '../../api/parcels'
import { normalizeApiError } from '../../utils/apiError'
import PageHeader from '../../components/PageHeader.vue'
import LoadingState from '../../components/LoadingState.vue'
import ErrorState from '../../components/ErrorState.vue'
import EmptyState from '../../components/EmptyState.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import AppIcon from '../../components/AppIcon.vue'

const parcels=ref([]); const loading=ref(true); const errorMessage=ref('')
const counts=computed(()=>({total:parcels.value.length,stored:parcels.value.filter(p=>p.status==='STORED').length,pickedUp:parcels.value.filter(p=>p.status==='PICKED_UP').length,expired:parcels.value.filter(p=>p.status==='EXPIRED').length}))
async function load(){loading.value=true;errorMessage.value='';try{parcels.value=await getCourierParcels()}catch(error){errorMessage.value=normalizeApiError(error,'包裹数据加载失败').message}finally{loading.value=false}}
onMounted(load)
</script>

<template><section><PageHeader title="快递员工作台" eyebrow="快递员" description="根据当前登录快递员的包裹记录展示工作概况。"><RouterLink class="btn-primary" to="/courier/store"><AppIcon name="store" :size="17" />包裹入柜</RouterLink></PageHeader><LoadingState v-if="loading" class="mt-6"/><ErrorState v-else-if="errorMessage" class="mt-6" :message="errorMessage" @retry="load"/><div v-else class="mt-6 space-y-6"><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article class="panel surface-dark p-6 sm:col-span-2 xl:col-span-2"><div class="flex items-start justify-between"><div><p class="text-xs font-bold uppercase tracking-[.14em] text-emerald-300">当前工作量</p><p class="metric-number mt-3 text-5xl font-black">{{counts.stored}}</p><p class="muted mt-2 text-sm">当前待用户取件的包裹</p></div><span class="grid size-11 place-items-center rounded-xl bg-white/10 text-emerald-300"><AppIcon name="parcels" :size="23" /></span></div><RouterLink class="btn-primary mt-7" to="/courier/store">新增包裹入柜 <AppIcon name="arrow" :size="16" /></RouterLink></article><article v-for="item in [{label:'已取件',value:counts.pickedUp,note:'已完成交付',color:'var(--color-info)'},{label:'已过期',value:counts.expired,note:'已进入过期状态',color:'var(--color-warning)'}]" :key="item.label" class="panel metric-card p-5"><span class="block h-1 w-8 rounded-full" :style="{background:item.color}"></span><p class="mt-4 text-xs font-bold uppercase tracking-[.1em] text-[var(--color-ink-500)]">{{item.label}}</p><p class="metric-number mt-2 text-3xl font-black">{{item.value}}</p><p class="mt-2 text-xs text-[var(--color-ink-500)]">{{item.note}}</p></article></div><div class="panel p-5 sm:p-6"><div class="flex justify-between"><div><p class="text-[10px] font-bold uppercase tracking-[.14em] text-[var(--color-brand)]">实时记录</p><h2 class="mt-1 text-lg font-black">最近包裹 <span class="ml-1 text-sm font-semibold text-[var(--color-ink-500)]">共 {{counts.total}} 个</span></h2></div><RouterLink class="section-link" to="/courier/parcels">查看全部 <AppIcon name="arrow" :size="15" /></RouterLink></div><EmptyState v-if="!parcels.length" class="mt-4" message="入柜后的包裹将显示在这里。"/><div v-else class="mt-4 grid gap-3 lg:grid-cols-2"><div v-for="parcel in parcels.slice(0,6)" :key="parcel.id" class="rounded-[var(--radius-sm)] border border-[var(--color-line)] bg-[var(--color-surface)] p-4"><div class="flex items-start justify-between gap-3"><p class="tracking-code">{{parcel.trackingNumber}}</p><StatusBadge :status="parcel.status"/></div><div class="mt-3 flex items-center gap-2 text-xs text-[var(--color-ink-500)]"><AppIcon name="stations" :size="15"/><span>{{parcel.stationName||'暂未分配'}}</span><span>·</span><strong class="text-[var(--color-ink-950)]">{{parcel.lockerCellCode||'—'}}</strong></div></div></div></div></div></section></template>
